### ISSUE TITLE
Add multiple font types

### ISSUE THREAD

**Issue by nothingismagick** [ipfs-shipyard/ipfs-css#10]
A solid font-pack would have a whole set of font-types:

-  .eot
- .svg
- .ttf
- .woff
- .otf
- .woff2

Woff2 is not enough, for reasons of compatibility.

![screen shot 2018-03-31 at 01 53 11](https://user-images.githubusercontent.com/35242872/38157335-5a8541c6-3486-11e8-8762-2bf9d11f66bf.png)

![screen shot 2018-03-31 at 02 05 42](https://user-images.githubusercontent.com/35242872/38157541-1f1d7624-3488-11e8-8fd8-f2e56e5d14d7.png)

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-css/pull/40 un-excludes woff, eot, otf formats when building -- these were the ones we were intentionally leaving out. (Other formats missing are because the fonts themselves are missing those formats.)
