### ISSUE TITLE
Upgrade font: Inter UI v3

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-css#29]
Inter UI v3 is a thing now. Review and upgrade if it so pleases you https://github.com/rsms/inter/releases/tag/v3.0

**Comment by jessicaschilling** [comment]
Need to analyze vis-a-vis https://github.com/ipfs-shipyard/ipfs-css/issues/6 and act accordingly.

**Comment by jessicaschilling** [comment]
3.13 actually: https://github.com/rsms/inter/releases/tag/v3.13

**Comment by jessicaschilling** [comment]
Addressing this - as well as updating to latest versions of Montserrat from https://github.com/JulietaUla/Montserrat - in https://github.com/ipfs-shipyard/ipfs-css/pull/40.

It looks as though we've simply duplicated the contents of the Montserrat and Inter repos, though, and I'm wondering why; unless I'm missing something, all we need are the completed font files themselves, not the source code for the fonts.
