### ISSUE TITLE
CSS Scrollbars 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-css#30]
I wonder if we should add some classes that unify scrollbars across all platforms (for use in overflow situations). 

Support for W3C Spec draft landed in Firefox 64:

> CSS Scrollbars: The [CSS Scrollbars Level 1 spec](https://drafts.csswg.org/css-scrollbars-1/) standardizes features for setting scrollbar width and color, which were originally only available in Internet Explorer. See CSS Scrollbars on [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars) and Scrollbars on [CSS Tricks](https://css-tricks.com/almanac/properties/s/scrollbar/) for more information.
> – https://hacks.mozilla.org/2018/12/firefox-64-released/

I imagine Chrome will follow eventually, but for now we could support it via Old WebKit Spec linked in Refs below (`::-webkit-scrollbar*`)

Refs.

- W3C Spec
  - https://drafts.csswg.org/css-scrollbars-1/
  - https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars
    - [#Browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars#Browser_compatibility)
  - https://css-tricks.com/almanac/properties/s/scrollbar/
- Old WebKit Spec (
  - https://css-tricks.com/custom-scrollbars-in-webkit/

**Comment by olizilla** [comment]
i've always seen ipfs-css as something to pair with a more general purpose css lib, so I'd say this is out of scope. We should try and keep ipfs-css to just things that make a UI feel like and IPFS UI.
