### ISSUE TITLE
Add glyph_switch.svg

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-css#31]
@akrych  created a new icon for https://github.com/ipfs-shipyard/ipfs-companion/issues/647 and we may want to add it to ipfs-css :)

> [glyph_switch.svg.zip](https://github.com/ipfs-shipyard/ipfs-css/files/2777155/glyph_switch.svg.zip)

[![2019-01-21--00-49-56](https://user-images.githubusercontent.com/157609/51446744-7e7b3300-1d16-11e9-8b51-196530d0ec29.png)](https://github.com/ipfs-shipyard/ipfs-css/files/2777155/glyph_switch.svg.zip)

It is bit big (~123KB), @hacdias any protips how to trim it down etc?

**Comment by lidel** [comment]
Opened it in Inkscape and.. SVG was big because it included all the other icons :upside_down_face:  (outside of the viewport)

Fixed version:
-  [glyph_switch_optimized.svg.zip](https://github.com/ipfs-shipyard/ipfs-css/files/2903029/glyph_switch_optimized.svg.zip) (only 462 bytes unzipped)

**Comment by lidel** [comment]
Opened it in Inkscape and.. SVG was big because it included all the other icons :upside_down_face:  (outside of the viewport)

Fixed version:
-  [glyph_switch_optimized.svg.zip](https://github.com/ipfs-shipyard/ipfs-css/files/2903029/glyph_switch_optimized.svg.zip) (only 462 bytes unzipped after [SCGO](https://jakearchibald.github.io/svgomg/))

**Comment by hacdias** [comment]
@lidel sorry. I didn't see this in January 😱 It seems 462 bytes is in the range of the other icons so I'd PR the repo with that icon

**Comment by olizilla** [comment]
Closing as per #32
