### ISSUE TITLE
Small arrow icons don't respect CSS fill changes

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-css#42]
See https://dl.dropboxusercontent.com/s/4se8lc2atpo36qf/cBPG7IhgSF.mp4 for an example of how this fails within Storybook for Web UI.

To do:
- Fix the arrow SVG
- Push as a minor update

**Comment by rafaelramalho19** [comment]
After creating https://ipfs-css-icons.netlify.app/?path=/story/icons--list&knob-Size=60&knob-Fill=rgba(55,26,199,1)&knob-Search=Small it seems that the problem is not in ipfs-css and it's in webui.

Moving this issue there.
