### ISSUE TITLE
Fonts: Il| O0

### ISSUE THREAD

**Issue by nothingismagick** [ipfs-shipyard/ipfs-css#6]
Just to throw some oil on the smoking embers of the typography battlefield, it should be clear that many sans-serif fonts do not make an OBVIOUS differentiation between the I, the l and the |. In normal usage, native speakers shouldn't have a problem understanding that **Illustration** is the capitalised letter after "H" and before "J" and it is followed by the lower-case letter "L" twice. 

I took a look at the **IPFS_brandbook.pdf** - and it suggested using Monserrat with Verdana as a fallback. Here in this repo, there is the introduction of Inter-UI. Of those three fonts, only Verdana distinguishes perfectly between `I`, the `l` and the `|`. Inter-UI is a total fail, because the `I` and the `l` are absolutely entirely indistinguishable.

This is moot for normal hashes, because adopting [base58](https://en.wikipedia.org/wiki/Base58) encoding solves the visual problem. Nevertheless, I bring this up as a font-fetishist because the reason we have different letters is, as with words, they help us build meaning. I would love to have a discussion here and think about ways forward. I see three:

1. Stick with the choices made. (status-quo)
2. Find better solutions. (discussion)
3. Modify an existing font. (hard work)

**Comment by jessicaschilling** [comment]
Need to investigate vis-a-vis https://github.com/ipfs-shipyard/ipfs-css/issues/6 and overall font choices, and act accordingly.

**Comment by jessicaschilling** [comment]
Closing this issue for now for two reasons:
- We'll be using the new InterUI v3 as in https://github.com/ipfs-shipyard/ipfs-css/issues/29, which does have slightly better differentiation
- And will be doing a more complete evaluation of font sets later this year (ideally) as part of a larger IPFS branding exercise.
