### ISSUE TITLE
Modify icons for consistency

### ISSUE THREAD

**Issue by nothingismagick** [ipfs-shipyard/ipfs-css#8]
One of these does not belong.

![screen shot 2018-03-30 at 20 25 50](https://user-images.githubusercontent.com/35242872/38148897-9e54db24-3458-11e8-86e9-6912a535eea5.png)

I propose thinning out the body of the links like this:
![link_new](https://user-images.githubusercontent.com/35242872/38149116-8e2e1dcc-3459-11e8-8726-903bb7921412.png)

**Comment by nothingismagick** [comment]
It seems like it would be obvious to have the IPFS logo here too...

**Comment by nothingismagick** [comment]
And this is so obvious that it hurts.

![ipfs-pin](https://user-images.githubusercontent.com/35242872/38153349-90ceabc4-346c-11e8-97cd-8b07784683dc.png)

**Comment by lidel** [comment]
I think these suggestions should be moved to https://github.com/ipfs-shipyard/ipfs-ui-style-guide/issues/3. 
@nothingismagick can you close this issue and add these comments there ?

**Comment by nothingismagick** [comment]
Funny you say that @lidel - I almost posted them there first, but then I found this repo and thought that it was actually more standardized, less like an experiment and looked like the right place to leave the commentary. I will, post these suggestions there too. However, as that repository references this one as the host of the icons, the css and the fonts I think it might be better to leave it in both places for the time being.

**Comment by jessicaschilling** [comment]
Closed by #40.
